[build-system]
requires = ["wheel-stub >= 0.4.2, < 1"]

build-backend = "wheel_stub.buildapi"

[tool.wheel_stub]
index_url = "https://carlosperate.github.io/arm-none-eabi-gcc-py-package/"

[project]
# Minimum imposed by wheel-stub; keep in sync with arm-none-eabi-gcc-toolchain/pyproject.toml.txt
requires-python = ">=3.8"
