[build-system]
requires = ["wheel-stub >= 0.4.0"]
build-backend = "wheel_stub.buildapi"

[tool.wheel_stub]
index_url = "https://carlosperate.github.io/arm-none-eabi-gcc-py-package/"

[project]
requires-python = ">=3.6"
