name: Deploy Package Repository

on: [workflow_dispatch, workflow_call]

jobs:
  build-package-repo:
    runs-on: ubuntu-latest
    name: 🏗️ Build Package Repository
    steps:
      - uses: actions/checkout@v7

      - name: Set Up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt --disable-pip-version-check

      - name: Build Static Simple Repository
        run: python tools.py repo-generator --repo "${{ github.repository }}"

      - name: Upload Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: simple_repository_static/


  deploy-package-repo:
    needs: build-package-repo
    name: 🚀 Deploy Package Repository
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


  check-package-repo:
    needs: "deploy-package-repo"
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-15-intel, macos-14, windows-2022]
        python: ["3.8", "3.14"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: "⤵️ ${{ matrix.os }} Py${{ matrix.python }}"
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dependencies
        run: pip install -r requirements.txt --disable-pip-version-check

      - name: Check with pip if packages are available without installing them
        run: python .github/workflows/check_repo_versions.py https://carlosperate.github.io/arm-none-eabi-gcc-py-package
