name: Build and Release

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        gcc:
          - "13.3.Rel1"
          - "13.2.Rel1"
          - "12.3.Rel1"
          - "12.2.Rel1"
          - "11.3.Rel1"
          - "11.2-2022.02"
          - "10.3-2021.10"
          - "10-2020-q4"
          - "9-2020-q2"
          - "9-2019-q4"
      fail-fast: false
    name: ${{ matrix.gcc }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Build all platform packages for this release
        run: python tools.py package-creator ${{ matrix.gcc }} --all

      - name: Get the package version
        if: github.event_name == 'workflow_dispatch'
        id: get_version
        run: |
          VERSION=$(python tools.py package-get-version ${{ matrix.gcc }})
          echo "version=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release on manual trigger (if it doesn't exist)
        if: github.event_name == 'workflow_dispatch'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          # body: ${{ matrix.gcc }}
          commit: ${{ github.sha }}
          skipIfReleaseExists: true
          replacesArtifacts: false
          artifacts: "dist/*.whl, dist/*.whl.metadata, dist/*.sha256, dist/*.tar.gz"
          token: ${{ secrets.GH_TOKEN }}


  update-simple-repository:
    needs: build-and-release
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/publish_repository.yml
